// Generate assets/js/config.js from environment variables at build time.
// Usage: `node scripts/gen-config.js` (Vercel Build Command can run this)
const fs = require('fs');
const path = require('path');

function getEnvJson(name){
  const v = process.env[name];
  if(!v) return null;
  try{ return JSON.parse(v); }catch(e){ return v; }
}

const cfg = {
  GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY || 'YOUR_GOOGLE_MAPS_API_KEY',
  FIREBASE_CONFIG: getEnvJson('FIREBASE_CONFIG') || null,
  WS_URL: process.env.FG_WS_URL || null,
  WATER_LEVEL_THRESHOLD: process.env.WATER_LEVEL_THRESHOLD ? parseFloat(process.env.WATER_LEVEL_THRESHOLD) : 0.7,
  SENSOR_COLLECTION: process.env.SENSOR_COLLECTION || 'sensor_readings',
  HELP_COLLECTION: process.env.HELP_COLLECTION || 'helpRequests',
  ALERTS_COLLECTION: process.env.ALERTS_COLLECTION || 'alerts',
  SAFE_DESTINATIONS: getEnvJson('SAFE_DESTINATIONS') || [{name: 'Municipal Safe Point', lat:20.0, lng:78.0}]
};

const out = `// Auto-generated by scripts/gen-config.js
const FG_CONFIG = ${JSON.stringify(cfg, null, 2)};
`;

const outPath = path.join(__dirname, '..', 'assets', 'js', 'config.js');
fs.writeFileSync(outPath, out, 'utf8');
console.log('Wrote', outPath);
